### PR TITLE
Refactor: pull repeated code up into functions

### PR DESCRIPTION
**Pull request by tildebyte**
NOTE: *Please* do not merge this, I need some feedback first.

The string args passed at [L251](https://github.com/miker2049/midigrid/compare/master...tildebyte:refactor-ii?expand=1#diff-fb16b47294507b6a958446a0672e6669R251) and [L290](https://github.com/miker2049/midigrid/compare/master...tildebyte:refactor-ii?expand=1#diff-fb16b47294507b6a958446a0672e6669R290) *should* be pointers to functions... only I can't seem to store e.g. `config:all_led_sysex` in a variable (I keep getting complaints about missing function args or something).

Help?

### CODE REVIEW

**Comment by catfact** [comment]
i haven't grokked the whole lib, but i'm guessing the colon syntax is tripping things up here. in function declaration, it adds a hidden "self" parameter as the first argument. (more details in this [SO question](https://stackoverflow.com/questions/4911186/difference-between-and-in-lua).)

passing around these "methods" as arguments could get pretty confusing. i'm not sure the "method" syntax is really needed here? it implies an OOP paradigm, but everything i'm seeing in this lib uses plain tables.

e.g., each `config` object is static, there's no mutable data that varies between different "instances" of a given config type, so there's no need to pass a hidden "self" argument around in the `config` functions (AFAICT.)

for another example, on L236:
```
function midigrid:all(brightness)
    local vel = brightness_handler(brightness)
    if midigrid.device then
       ... 
```

`midigrid.device` is a static field here, right? if `midigrid` were a class, you would use `self.device`, and this implies that `midigrid`  is used as a metatable or "template" for new objects... if you want examples of this paradigm you could check out e.g. `Grid` class in norns repo.


but also to be clear, there's absolutely nothing wrong with the all-static approach!

**Comment by miker2049** [comment]
Was finally looking at this and was about to suggest trying to replace the colons with dots and see if that would work!  

The nature in general of this library, as a kind of shim, I think benefits from the all-static type of approach.  The only time in the current API where colon notation is used is when it is simply being used to _look_ like the way it is used in scripts interacting with midi or the grid, even if this is misleading as `midigrid` is not a full blown class really, in the way @catfact is saying, and is in fact really just a wrapper over the midi devices class (I think this is the right way to put it??).  This seems to be stable in general.

So I think it is confusing here because the sysex stuff _feels_ like a method to pass insofar as it looks the way the norns ecosystem _only conventionally_ uses the colon syntatic sugar.  But really here you just want to pass on a function for handling leds, not create an alias for the config's own method to itself.  

Does replacing the colons with dots work here?

**Comment by tildebyte** [comment]
@catfact, @miker2049; It had occurred to me that that might be the case... the sticky part here is that some (the ones in questions actually) of the `config` methods use `self` (have to, in order to access inner members, unless I'm Doing It Wrong :P ) - but maybe the dot notation along with passing `config` as arg 1 will work; I'll try it out.

**Comment by tildebyte** [comment]
@catfact, @miker2049; Nice, thanks!

I had an epiphany that all I needed was the *data* returned by the function, and not the function itself.

Also noticed another refactor, in handling the quad select buttons.

Tested locally with my fates and LP Pro running loom (256) and meadowphysics (128)

Almost forgot to mention - ready for review/merge

**Pull request merged**
